openapi: 3.0.3
info:
  title: Library API
  version: '1.2.0'
  description: STD22086
servers:
  - url: https://library.com
    description: Main server
tags:
  - name: Books
    description: Operations related to books
  - name: Authors
    description: Operations related to authors
paths:
  '/books':
    get:
      tags: [Books]
      summary: Retrieve a list of books
      description: Retrieve a list of books from the library. You can apply filters and pagination
      operationId: getBooks
      parameters:
        - $ref: '#/components/parameters/queryPagination'
        - $ref: '#/components/parameters/queryPageSize'
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
    put:
      summary: Create/Update books
      operationId: crupdateBooks
      tags: [Books]
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
  '/books/{bookId}/authors/{authorId}':
    put:
      tags: [Books]
      summary: Update author of a book
      operationId: updateBookAuthor
      parameters:
        - in: path
          name: bookId
          description: Book ID
          required: true
          schema:
            type: string
        - in: path
          name: authorId
          description: Author ID
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
  '/books/authors':
    put:
      tags: [Books]
      summary: Associate authors with books
      operationId: associateAuthorsWithBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBookAuthor'
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
  '/books/import':
    post:
      tags: [Books]
      summary: Import books from Excel or JSON
      operationId: importBooks
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                books:
                  type: array
                  items:
                    $ref: '#/components/schemas/BookImport'
          multipart/form-data:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ImportBook'
                - $ref: '#/components/schemas/ImportAuthor'
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
  '/books/export':
    get:
      tags: [Books]
      summary: Export books to Excel or JSON
      operationId: exportBooks
      parameters:
        - name: format
          in: query
          description: Format of the exported data (json or excel)
          schema:
            type: string
            enum: [json, excel]
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
  '/authors':
    get:
      summary: Get authors
      description: Retrieve a list of authors with optional pagination.
      operationId: getAuthors
      tags: [Authors]
      parameters:
        - $ref: '#/components/parameters/queryPagination'
        - $ref: '#/components/parameters/queryPageSize'
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
    put:
      summary: Create/Update authors
      operationId: createOrUpdateAuthors
      tags: [Authors]
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
    delete:
      summary: Delete authors
      description: Delete all authors in the system.
      operationId: deleteAuthors
      tags: [Authors]
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
  '/authors/{aId}':
    delete:
      summary: Delete an author
      operationId: deleteAuthor
      tags: [Authors]
      parameters:
        - name: aId
          in: path
          description: Author ID to be deleted
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
  '/authors/import':
    post:
      tags: [Authors]
      summary: Import authors from Excel or JSON
      operationId: importAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authors:
                  type: array
                  items:
                    $ref: '#/components/schemas/AuthorImport'
          multipart/form-data:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ImportBook'
                - $ref: '#/components/schemas/ImportAuthor'
      responses:
        200:
          $ref: '#/components/responses/Response200'
        400:
          $ref: '#/components/responses/Response400'
        403:
          $ref: '#/components/responses/Response403'
        404:
          $ref: '#/components/responses/Response404'
        500:
          $ref: '#/components/responses/Response500'
components:
  responses:
    Response200:
      description: Response 200 (Success)
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/responses/DefaultResponse'
              - type: object
                properties:
                  status:
                    properties:
                      code:
                        type: integer
                        example: 200
                      message:
                        type: string
                        example: 'Success'
                  body:
                    type: object
                    properties:
                      data:
                        type: object
    Response400:
      description: Response 400 (Bad Request)
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/responses/DefaultResponse'
              - type: object
                properties:
                  status:
                    properties:
                      code:
                        type: integer
                        example: 400
                      message:
                        type: string
                        example: 'Bad Request'
                  body:
                    type: object
                    properties:
                      error:
                        type: string
    Response403:
      description: Response 403 (Forbidden)
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/responses/DefaultResponse'
              - type: object
                properties:
                  status:
                    properties:
                      code:
                        type: integer
                        example: 403
                      message:
                        type: string
                        example: 'Forbidden'
                  body:
                    type: object
                    properties:
                      error:
                        type: string
    Response404:
      description: Response 404 (Not Found)
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/responses/DefaultResponse'
              - type: object
                properties:
                  status:
                    properties:
                      code:
                        type: integer
                        example: 404
                      message:
                        type: string
                        example: 'Not Found'
                  body:
                    type: object
                    properties:
                      error:
                        type: string
    Response500:
      description: Response 500 (Internal Server Error)
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/responses/DefaultResponse'
              - type: object
                properties:
                  status:
                    properties:
                      code:
                        type: integer
                        example: 500
                      message:
                        type: string
                        example: 'Internal Server Error'
                  body:
                    type: object
                    properties:
                      error:
                        type: string
    DefaultResponse:
      description: Default response for all responses
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Success'
              body:
                type: object
                additionalProperties: false
                properties:
                  result:
                    type: string
                    example: 'success'
                  data:
                    type: object
                    properties:
                      books:
                        type: array
                        items:
                          $ref: '#/components/schemas/Book'
                      authors:
                        type: array
                        items:
                          $ref: '#/components/schemas/Author'
                required:
                  - result
                  - data
  parameters:
    queryPagination:
      name: page
      in: query
      description: Page number for paginated results (defaults to 1)
      required: false
      schema:
        type: integer
        default: 1
    queryPageSize:
      name: pageSize
      in: query
      description: Number of records per page (defaults to 50, max is 100)
      required: false
      schema:
        type: integer
        default: 50
    pathPagination:
      name: page
      in: path
      description: Page number for paginated results (defaults to 1)
      required: true
      schema:
        type: integer
    pathPageSize:
      name: pageSize
      in: path
      description: Number of records per page (defaults to 50, max is 100)
      required: true
      schema:
        type: integer
  schemas:
    BookImport:
      type: object
      properties:
        books:
          type: array
          items:
            $ref: '#/components/schemas/BookWithoutID'
    BookWithoutID:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum: [ROMANCE, COMEDY, OTHER]
        releaseDate:
          type: string
          format: date
    AuthorImport:
      type: object
      properties:
        authors:
          type: array
          items:
            $ref: '#/components/schemas/AuthorWithoutID'
    AuthorWithoutID:
      type: object
      properties:
        authorName:
          type: string
        sex:
          type: string
          enum: [M, F]
    ImportAuthor:
      type: object
      properties:
        authorName:
          type: string
        sex:
          type: string
          enum: [M, F]
    ImportBook:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum: [ROMANCE, COMEDY, OTHER]
        releaseDate:
          type: string
          format: date
        idAuthor:
          type: integer
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        pageNumbers:
          type: integer
        topic:
          type: string
          enum: [ROMANCE, COMEDY, OTHER]
        releaseDate:
          type: string
          format: date
    Author:
      type: object
      properties:
        id:
          type: string
        authorName:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
    CrupdateBook:
      allOf:
        - $ref: '#/components/schemas/Book'
        - type: object
          properties:
            author:
              type: string
    Sex:
      type: string
      enum: [M, F]
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
          description: Book ID to associate with the author
        authorId:
          type: string
          description: Author ID to associate with the book
